[Clipboard] getData implementation added
flutter-tizen/engine pull request #65
Opened 2021-04-15 10:06 UTC by pkosko

[Before] Clipboard.getData feature was not implemented

[After] Dart code below is able to gather system clipboard data:
      Future<ClipboardData?> d = Clipboard.getData(Clipboard.kTextPlain);
      void dataCallback(ClipboardData? d) {
        if (d != null) {
          String? text = d.text;
          if(text != null) {
            print("Clipboard data $text");
          }
        }
      }
      d.then(dataCallback);

[TODO] Need to consider adding some mechanism of synchronization of access to native cbhm API
to provide proper behaviour in case of multiple calls

Change related to PlatformChannel Clipboard.getData() part of https://github.sec.samsung.net/f-project/home/issues/35
https://github.sec.samsung.net/f-project/home/issues/35

2021-04-15 10:15 UTC, pkosko commented
Necessary dependency was added to tizen_tools with PR https://github.com/flutter-tizen/tizen_tools/pull/8

2021-04-15 11:01 UTC, rwalczyna requested changes

2021-04-15 11:02 UTC, rwalczyna commented on shell/platform/tizen/channels/platform_channel.cc
> +      result->Error(kUnknownClipboardError, "Failed to gather data.");
Also `result` is invalidated in line 89.

2021-04-15 11:05 UTC, swift-kim commented
The CI build [failed](https://dev.azure.com/flutter-tizen/flutter-tizen/_build/results?buildId=126&view=logs&jobId=b18d3a6b-f201-507d-63b2-3021204a73d1&j=b18d3a6b-f201-507d-63b2-3021204a73d1&t=6cd5b392-a25d-533a-aedc-65d8e9b3a2f60). Where can we find the `cbhm.h` header?

2021-04-15 11:05 UTC, swift-kim commented
Sorry. I was not aware of the tizen_tools PR!

2021-04-15 11:16 UTC, pkosko commented on shell/platform/tizen/channels/platform_channel.cc
> +      result->Error(kUnknownClipboardError, "Failed to gather data.");
Good point, I will fix it!

2021-04-15 16:18 UTC, pwasowski2 commented on shell/platform/tizen/channels/platform_channel.cc
> +      return;
Shouldn't `is_processing` be set to `false` before return?

2021-04-15 16:18 UTC, pwasowski2 commented on shell/platform/tizen/channels/platform_channel.cc
> +    const rapidjson::Value& format = call.arguments()[0];
Consider moving the body of this "if" to a separate method to make `PlatformChannel::HandleMethodCall` shorter.

2021-04-15 16:18 UTC, pwasowski2 commented on shell/platform/tizen/channels/platform_channel.cc
> +    struct method_data_t {
Shouldn't we use Google coding style here and name this `MethodData`?

2021-04-16 04:17 UTC, swift-kim commented
Tip: If you're using VS Code you can easily format your code by applying the following.

- Enable "Format on Save" in the settings
- Install the "C/C++" extension
- Add `"C_Cpp.clang_format_fallbackStyle": "Google"` to the workspace settings

2021-04-16 04:27 UTC, swift-kim commented
Thank you for your contribution!

As far as I can see the CBHM API is mobile-only, so probably the embedder with this change will not even load on non-mobile devices (e.g. watch) because libcbhm will not exist on those devices. I'm currently thinking about how to release different embedders for different profiles (mobile/wearable/tv/iot) and integrate with the flutter-tizen tool. The design is not fixed yet but it will use compiler switches like `#ifdef TV_PROFILE`. You will have to wait a while until it is implemented for your change to be merged. Otherwise you can suggest any other ways to deal with the problem!

2021-04-27 05:17 UTC, swift-kim commented
Now #67 has been merged and you can guard any code that is for mobile only using `#ifdef MOBILE_PROFILE` or `#if defined(MOBILE_PROFILE)`. Also you will have to change `BUILD.gn` as follows:

```patch
diff --git a/shell/platform/tizen/BUILD.gn b/shell/platform/tizen/BUILD.gn
index 1ea9bcf30..bb9837748 100644
--- a/shell/platform/tizen/BUILD.gn
+++ b/shell/platform/tizen/BUILD.gn
@@ -38,6 +38,7 @@ config("tizen_rootstrap_include_dirs") {
     "$custom_sysroot/usr/include",
     "$custom_sysroot/usr/include/appfw",
     "$custom_sysroot/usr/include/base",
+    "$custom_sysroot/usr/include/cbhm",
     "$custom_sysroot/usr/include/dlog",
     "$custom_sysroot/usr/include/ecore-1",
     "$custom_sysroot/usr/include/ecore-evas-1",
@@ -141,6 +142,10 @@ template("embedder_for_profile") {
       libs += [ "ecore_wl2" ]
     }

+    if (target_name == "mobile") {
+      libs += [ "cbhm" ]
+    }
+
     cflags_cc = [
       "-Wno-newline-eof",
       "-Wno-macro-redefined",
```

2021-04-27 11:55 UTC, pkosko commented
Unfortunately, implementation using public CBHM API has issue which disqualifies it as stable copy/paste support even on mobile only. In case of Flutter application using simple TextField in its UI:
```
TextField(
              decoration: InputDecoration(
                border: OutlineInputBorder(),
                hintText: 'Enter a search term',
              ),
            ),
```
, framework automatically calls Clipboard.getData() method during first run of application. According to my analysis and testing, in such case native API (cbhm_selection_get) does not trigger success callback (cbhm_selection_data_cb), nor return any error. Because current implementation is based on mutexes to protect accessing from different threads, this scenario causes a deadlock-like API state which always return error "Already processing in other thread" (because is_processing flag was not released in callback).  I've tried to workaround this problem, but my all ideas were very ugly hacks which also does not guarantee memory safety and proper API behaviours in all cases.

Because of above issue of native API, I think that it is better to not include this PR to final code.

2021-04-27 11:56 UTC, closed without merging

2021-04-27 11:57 UTC, pkosko commented
I've prepared much simpler implementation https://github.com/flutter-tizen/engine/pull/76 which uses naive in-application clipboard. Please share your opinion.